### ISSUE TITLE
Guidelines and best practices

### ISSUE THREAD

**Issue by Aayush9029** [Sankalpa-Acharya/DOS#1]
Not much of an issue but a suggestion.

- you seem to code in a "bash" style removing spaces between equal to sign `=`  https://github.com/Sankalpa-Acharya/DOS/blob/6d4455e8ae1ebfe9cc710ffa8181a5e26beb7d6b/main.py#L35
> I recommend using some sort of linter! Depending on your editor this should be relatively easy to setup! 
```python3
your_variable_name = your_value
# note the space in between
```
- function names seem to be a little inconsistent https://github.com/Sankalpa-Acharya/DOS/blob/6d4455e8ae1ebfe9cc710ffa8181a5e26beb7d6b/helper.py#L14
> Function names should be lowercase, with words separated by underscores as necessary to improve readability.

**I'd highly recommend you to take a look at [this pep8 style guide](https://www.python.org/dev/peps/pep-0008/).**

*This is just a suggestion! But this will be super helpful when you want to branch out and collaborate on projects! :🎉*

Happy coding! Looking forward more projects!!!!

**Comment by Sankalpa-Acharya** [comment]
Thank you ❤️ , Will implement from now
